# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,9,12,15],np.int32)

In [3]:
myarr

array([ 3,  6,  9, 12, 15])

In [4]:
newarr = np.array([[9,8,7,6,5],[0,1,2,3,4]],np.int16)

In [5]:
print(newarr)

[[9 8 7 6 5]
 [0 1 2 3 4]]


In [6]:
# Get shape
newarr.shape


(2, 5)

In [7]:
#get dimension dimension like in cube you can go in 3 direction
newarr.ndim

2

In [8]:
newarr.dtype

dtype('int16')

In [9]:
newarr.itemsize

2

In [10]:
newarr.size

10

In [11]:
#nbytes=total_size= size*item_size
newarr.nbytes

20

# Accesing/changing specific elements,rows,coloumn,etc

In [12]:
#get a specific element
newarr[1,3]

3

In [13]:
#get a specific row
newarr[0,:]

array([9, 8, 7, 6, 5], dtype=int16)

In [14]:
#get a specific coloumn
newarr[:,0]

array([9, 0], dtype=int16)

In [15]:
#getting a liitle lot more fancy [startindex:endindex:stepsize]
newarr[0, 1:4:2]      

array([8, 6], dtype=int16)

# 3d examples

In [16]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15]])

In [17]:
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]


In [18]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
b[:,1,1]

array([4, 8])

In [20]:
#replace 
b[:,1,1]=[10,14]
print(b)

[[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [ 7 14]]]


In [21]:
#all 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#all 1's matrix
np.ones((4,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [23]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
#any other number(full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [25]:
#or
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [26]:
#random decimal numbers
np.random.rand(1,1,3)

array([[[0.55936946, 0.49227912, 0.31407978]]])

In [27]:
#random Integer values
np.random.randint(7,size=(3,3))

array([[6, 6, 2],
       [2, 3, 4],
       [3, 5, 0]])

In [28]:
np.random.randint(4,7,size=(1,4))

array([[5, 5, 4, 4]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [46]:
#arange is used as range function in python
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [49]:
#here it is used as np.linspace(starting,endpoint,how many numbers)
np.linspace(1,16,num=11)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ])

In [30]:
#to repeat
arr=np.random.rand(1,3)
r1=np.repeat(arr,3,axis=0)
print(r1)

[[0.88688055 0.17618944 0.39487098]
 [0.88688055 0.17618944 0.39487098]
 [0.88688055 0.17618944 0.39487098]]


In [31]:
# matrix=np.ones((1,1))
# print(matrix)
# r1=np.repeat(matrix,5,axis=1)
# print(r1)
# r2=np.repeat(r1,5,axis=0)
# print(r2)
matrix=np.ones((5,5))
print(matrix)
z=np.zeros((3,3))
z[1,1]=9
print(z)
matrix[1:-1,1:-1]=z
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying

In [32]:
#copying function
x=np.array([1,2,3])
y=x.copy()
print(y)

[1 2 3]


In [33]:
y=np.array([4,5,6])
print(y)
print(x+y)

[4 5 6]
[5 7 9]


In [34]:
print(x**3)

[ 1  8 27]


In [35]:
#using the cos function
print(np.cos(x))

[ 0.54030231 -0.41614684 -0.9899925 ]


#### Linear Algebra 

In [36]:
p=np.full((2,3),1)
print(p)
q=np.full((3,2),2)
print(q)
r=np.matmul(p,q)
print(r)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [37]:
#find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [38]:
g=np.full((3,3),6)
h=np.identity(3)
# h=np.matmul(g,i)
np.min(x,axis=0)

1

In [39]:
np.max(x)

3

In [40]:
np.sum(x)

6

In [41]:
 print(g.reshape(1,9))

[[6 6 6 6 6 6 6 6 6]]


In [42]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load data from file

In [44]:
filedata=np.genfromtxt('Data.txt' , delimiter=',')
print(filedata)

FileNotFoundError: Data.txt not found.

In [ ]:
 v1[[1,2,3]]

### Basic Maths


In [51]:
#addition //pther functions are subs,multi,divide,power,exp
a=np.array([[1,2,3],[4,5,6]])
a=np.add(a,1)
print(a)

[[2 3 4]
 [5 6 7]]


In [52]:
a+1

array([[3, 4, 5],
       [6, 7, 8]])

In [54]:
#a**2 or
np.power(a,2)

array([[ 4,  9, 16],
       [25, 36, 49]], dtype=int32)

In [55]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

In [56]:
np.add.reduce(a,axis=0)  #summing of rowa // by default it will apply in first axis i.e axisn=0

array([ 7,  9, 11])

In [57]:
#summing of columns
np.add.reduce(a,axis=1)

array([ 9, 18])

In [58]:
a.sum(axis=0)

array([ 7,  9, 11])

In [59]:
a.sum()

27

In [60]:
a.sum(axis=1)

array([ 9, 18])

### Broadcasting

In [61]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [63]:
b=np.array([7,8,9])
print(b)

[7 8 9]


In [64]:
a+b

array([[ 8, 10, 12],
       [11, 13, 15]])